### ISSUE TITLE
[BUG] Program repair light bulb

### ISSUE THREAD

**Issue by remva** [Felienne/hedy#1469] opened 2021-12-05 14:05 UTC
The program repair light bulb doesn't light up in Firefox (when trying on Linux). Her hair is supposed to light up in yellow, but that only works on Google Chrome for me. The button still works regardless.

![image](https://user-images.githubusercontent.com/77205246/144749671-fb8b6725-6ad7-4694-a691-ba91f510733b.png)

**Comment by bjorn3** [comment] 2021-12-05 15:24
In CSS 2.1 the `content` attribute only works on `:before` and `:after` pseudo-elements. The CSS 3 Generated and Replaced Content Module working draft allows it on all elements, like chrome, but it is just a working draft and firefox probably didn't implement it. An empty div in combination with the `background` css attribute should work fine though.

https://stackoverflow.com/questions/11173991/content-attribute-of-img-elements
https://www.w3.org/TR/css-content-3/#content

**Comment by TiBiBa** [comment] 2022-02-02 15:31
I'm unable to re-produce this bug in either Firefox, Chrome or Safari!

**Comment by bjorn3** [comment] 2022-02-02 15:39
Can't reproduce it either on Firefox. Probably fixed in either Hedy or Firefox.

**Closed** 2022-02-02 15:40 UTC
Labels: good first issue
