### ISSUE TITLE
[BUG] Using a variable name within a string before assignment crashes program

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#2961] opened 2022-06-24 10:55 UTC
**Describe the bug**
When trying to print a string with a variable name that is assigned after the printing results in an error. This shouldn't happen as we are also allowed to simply print the string. We found this bug due to debugging the Parsons exercises in level 3.

**Code example**
```
print The new school year at Hogwarts is starting!
print The sorting hat is ready to sort you into one of the houses.
houses is Gryffindor, Hufflepuf, Ravenclaw, Slytherin
sleep 2
print And it is houses at random
```

**Expected behavior**
The program should be valid.

**Comment by Felienne** [comment] 2022-06-24 12:53
Yeah... I know! This is a duplicate of an old one #1503

**Closed** 2022-06-24 12:53 UTC
