### ISSUE TITLE
Translate the keywords `left` and `right` to the current language

### ISSUE THREAD

**Issue by boryanagoncharenko** [Felienne/hedy#1876] opened 2022-02-01 17:15 UTC
In Hedy level 1, the user can use the `turn` command with the literals `left` and `right`. While the `turn` command can be translated to the current language, the keywords `left` and `right` cannot:

Level 1:
```
adelante 50
girar left
```

1. Add support for translating `left` and `right` to the current language
2. Ensure that the translation of `left` and `right` is used in error messages. For example if in level 1 the user puts an invalid value, the error message should have the words left and right translated properly.

![Screenshot 2022-02-01 at 19 14 02](https://user-images.githubusercontent.com/3010723/152017054-d2e6dacd-dffb-4598-917c-0ff9a337691b.png)

Level 1:
```
girar something
```

**Comment by Felienne** [comment] 2022-02-08 13:32
I think this is a duplicate of #1716? Because this is more extensive I am closing the other one

**Closed** 2022-03-11 10:21 UTC
