### ISSUE TITLE
Double echo in level-1

### ISSUE THREAD

**Issue by MarinusVanDijk** [Felienne/hedy#160] opened 2021-02-18 08:28 UTC
![image](https://user-images.githubusercontent.com/37830964/108326890-10421c80-71cb-11eb-80a5-d55cbe861a72.png)

Then hit the run it button not the enter button.

![image](https://user-images.githubusercontent.com/37830964/108327076-454e6f00-71cb-11eb-8870-9a64af63ef02.png)

Then hit the enter button after typing Hallo instead of Hello

Results in:

![image](https://user-images.githubusercontent.com/37830964/108327226-6f079600-71cb-11eb-8515-357999815641.png)

I expected only one Hallo.

**Comment by Felienne** [comment] 2021-02-18 08:31
Not sure what happens here and how we could prevent it, but this again is not a thing we have seen kids try, so it is not high prio at the moment.

**Comment by MarinusVanDijk** [comment] 2021-02-18 09:16
Perhaps the run code button must be suppressed when a question is answered? But is it better to fix the underlaying error. This error can pop up in no time somewhere else. I think the answer is stored twice because the answer variable is not made empty.

**Comment by fpereiro** [comment] 2021-02-18 09:50
Hi @MarinusVanDijk . This should be fixed by fixing this issue: https://github.com/Felienne/hedy/issues/147 . I'll post an update here when the fix is committed.

**Comment by Felienne** [comment] 2021-02-19 06:20
Yeah in essence this bug is a duplicate of #147, it describes a fix to this issue, so I think we can close this one.

**Closed by Felienne** 2021-02-19 06:20 UTC
