### ISSUE TITLE
[BUG] Can't access public profile

### ISSUE THREAD

**Issue by das-g** [Felienne/hedy#1822] opened 2022-01-27 19:41 UTC
**Describe the bug**

I've signed up for a user account, verified my email address by clicking on the link in the e-mail I then got and I've created and saved a public profile for my account. When I try to access that public profile at https://www.hedycode.com/user/das-g, I get an angry-/unhappy-looking Hedy figure and the message "Looks like you aren't authorized..." or in German "Scheint als bist du nicht authorisiert...".

![image](https://user-images.githubusercontent.com/97746/151431517-d917fe48-2feb-4c79-ab08-cf19a1ebd448.png)

![image](https://user-images.githubusercontent.com/97746/151431744-4da9bd28-415d-40f0-9ae7-8d0626c65683.png)

This is the case whether I'm logged in or not, and also with various browsers.

**Paste the Hedy code & level**
I think this is independent of code and level.

**Expected behavior**
The profile should either be publicly accessible, or the profile settings page should give some indication why it is not.

**What machine and browser you were using (optional)**

Tried with these browsers:
- Firefox 96.0.1 (64-bit)
- Chromium Version 97.0.4692.99 (Official Build, ungoogled-chromium) (64-Bit)
- GNOME Web 41.3

Output of `nix-shell -p nix-info --run "nix-info -m"`:
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.92, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `"nixos-22.05pre347261.6d8215281b2, nixos-unstable-21.03pre257780.e9158eca70a"`
 - channels(das-g): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ThomasKluiters** [comment] 2022-01-30 15:10
It seems like #1786 made the public profiles.. not so public anymore, @TiBiBa - was this intentional?

**Comment by TiBiBa** [comment] 2022-01-30 15:47
> It seems like #1786 made the public profiles.. not so public anymore, @TiBiBa - was this intentional?

I'm unable to re-produce this error? Public profile should only be available to logged in users - this is intentional. But when logged in I'm not able to re-produce this.

**Comment by TiBiBa** [comment] 2022-01-30 15:53
I did just fix another issue where the `.lower()` functional on the called username was incorrect. But I don't think this causes this error as an "user_not_private" message should be returned instead.

**Comment by ThomasKluiters** [comment] 2022-01-30 15:56
@TiBiBa I see! I stand corrected then :) You can reproduce this by visiting your own public profile, I think this error only occurs when you try to visit your own profile - not others - I am free to visit das-g's profile, for example.

I can look into this :)

**Comment by das-g** [comment] 2022-01-30 16:02
> I'm unable to re-produce this error? Public profile should only be available to logged in users - this is intentional. But when logged in I'm not able to re-produce this.

I can't reproduce it anymore, either: Now my profile https://www.hedycode.com/user/das-g is accessible when I'm logged in (as user `das-g`). I'm sure that when I reported the issue, this was not the case, as can be seen in my first screenshot. (If I remember correctly, this was shortly after e-mail address verification. Dunno if that could have caused temporary troubles with, maybe, session cookies or something?)

When I'm not logged in, I still get the error message. But as you state, that's intentional. (Though for that case, maybe a more helpful error message like "You need to be logged in to few profiles." should be considered.)

**Comment by ThomasKluiters** [comment] 2022-01-30 16:05
Seems like this issue is a bit more complicated than expected - I am now facing the issue @das-g *was* facing, I receive a "je mag niet op deze pagina zijn" (500) error. I tried re-logging, upper, lower cases. Strange!

**Comment by TiBiBa** [comment] 2022-01-30 16:09
> @TiBiBa I see! I stand corrected then :) You can reproduce this by visiting your own public profile, I think this error only occurs when you try to visit your own profile - not others - I am free to visit das-g's profile, for example.
> 
> I can look into this :)
> 
> ![image](https://user-images.githubusercontent.com/8137941/151707043-14630a94-a1f8-4f13-a12d-2310818b3d65.png)

I'm still unable to re-produce this; even when visiting my own profile. Would be great if you could take a look, please keep in mind that I already fixed the uppercase issue in #1850 (still to be merged).

**Comment by ThomasKluiters** [comment] 2022-02-04 13:15
This seems to be fixed with #1850

**Closed by ThomasKluiters** 2022-02-04 13:15 UTC
