### ISSUE TITLE
[BUG] = should work without space

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1866] opened 2022-01-31 16:44 UTC
**Describe the bug**
No space allowed between `=` and variable. For `is` this makes some sense but for `=` it should be allowed

**Paste the Hedy code & level**

f.e. level 9 (but I am sure it is true for other levels too)
```
score= 0
print score
````

**Comment by thjazi39** [comment] 2022-02-23 10:24
Hello,
I tried to reproduce this bug to try to solve it, but I didn't succeed to get it.

I tested from level 6 to level 17, with a space or not before = ( and the same after = )

I think that when there was the update of Lark, it solved this bug, indeed, in the file hedy/grammars/level6-Additions.lark we have :
```
equality_check_is: textwithoutspaces _SPACE _IS _SPACE (textwithoutspaces | quoted_text)
equality_check_equals: textwithoutspaces _EQUALS (textwithoutspaces | quoted_text)
```
And that should have solved the problem!

**Comment by Felienne** [comment] 2022-02-23 10:30
Haha isn't this a great way to close bugs, by not doing anything?! :) 

This is solved not by the new version of Lark I think (because it works on hedycode.com too) but indeed because _EQUALS now allows for spaces:

https://github.com/Felienne/hedy/blob/476642754658d2fcc3557f26d440541022ec6e16/grammars/level1.lark#L13

**Comment by thjazi39** [comment] 2022-02-23 13:00
Ok, I hadn't seen what _Space was referring to, but indeed!

On the other hand, while checking that it does not pose problem in the string, I found that it worked well without space, but not with :

```
a is 'b=2'
print a
```
=> Work 

```
a is 'b = 2'
print a
```
=> a is not a Hedy level 7 command. Did you mean if?

But since this does not concern only the = but any assignment of string containing a space in a variable, I will open a new issue and close it

**Closed by thjazi39** 2022-02-23 13:00 UTC

**Comment by Felienne** [comment] 2022-02-23 14:31
> Ok, I hadn't seen what _Space was referring to, but indeed!

Make sense, all levels are composed together but not everyone might be aware of that.
