### ISSUE TITLE
unexpected `bad input` error in level 6 [BUG]

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#1721] opened 2022-01-18 15:58 UTC
**Describe the bug**
When I run the code below I get the error: `Er ging iets fout bij het uitvoeren van het programma. bad input`

```
eten is ask 'wat wilt u bestellen'
if eten is taart print 'ok'
print 'taart'

```
I expected the code to print 'taart' (or 'ok' and 'taart')

![image](https://user-images.githubusercontent.com/10562903/149972444-21249736-505e-4b29-808f-0426772fa186.png)

**Comment by Felienne** [comment] 2022-01-18 16:16
Weird!! I will look into this!

**Comment by Felienne** [comment] 2022-01-18 16:19
For now I can recommend using something in this shape, which does work:

```
eten is ask 'wat wilt u bestellen'
if eten is taart
print 'ok'
else
print 'geen taart dus'
```

**Comment by Felienne** [comment] 2022-01-20 10:47
Ok, I have looked into this and the issue is interesting and tricky!

```
eten is ask 'wat wilt u bestellen'
if eten is taart print 'ok'
print 'taart'
```

Remember that we allow line breaks in if-else commands for readability and that we do not distinguish assignment with `is` from comparison with `is`. So that means that this code is transformed to Python like this:

if (eten == "taart print 'ok'") <- comparison "eats" the print statement
    print 'taart'

One mistake is that we did not generate this Python properly causing the bad input error, but the real issue is that if we allow `if` with linebreaks, *without* else, and also allow comparing words with spaces (`if ridder is de groene ridder` , we can never tell these two apart.

I can think of a few dirty hacks and fixes but the root cause will remain. So one of these will have to be dropped to properly fix this:

1. We no longer allow linebreaks in level 5 and 6, if needs to go on one line again
2. We revert the change of allowing comparing to words with spaces, like `if ridder is de groene ridder`
3. We only allow `if` in level 5 and 6 *only* when used with together with `else`.
4. We mandate newlines after the comparison from level 5: 

```
if eten is taart
print 'ok'
print 'taart'
```

I tend to lean to 3, because it is easiest to implement and does not prevent kids from doing anything, but it will make some codes a bit more complex because the else needs to be added always. I know we discussed 4 before and @OnnoEbbens found it made the code too programmy which I tend to agree with, and as you can see from the example above it it really confusing without indentation.

Tagging @MarleenGilsing so she can also comment!

**Comment by OnnoEbbens** [comment] 2022-01-20 17:26
Thanks for sorting this out! In my opinion the best option would be the one with the least restrictions for the users. For me option 1, 2 and 3 all feel similar in that sense. I still don't like the 4th option.

I also have another idea, I might be completely off so please correct me if I am wrong. Now in level 4 `ask` and `print` require quotation marks but the text string after `is` does not require quotation marks (e.g. `name is john`). What if we change level 4 in such a way that every string should be a string (e.g. `name is 'john'`). This might simplify the conversion to Python of the `if` statement in level 5 and 6 and solve this issue. 

The proposed change also creates a clear difference between variables and text. Now I often see students writing an `if` where they compare two variables that have not been defined (e.g. `if name is person print 'nice name'`). In the current setting this does not raise an error because the check is translated to `if 'name' =='person'` which is always false. With the proposed change this will raise a name error. I am aware that this makes level 4 and 5 a bit more complex but I think it will help students to distinguish between variables and text. Again, I lack the overview to know all the effects of this change so please let me know if this is not feasible.

**Comment by Felienne** [comment] 2022-01-20 19:42
For me (as programmer) this make it a whole lot easier to make! So from that perspective I am in favor, but I suspect it might be hard for kids to not forget. What do you think @MarleenGilsing? We could allow if for single words (without spaces) but give a warning there, so kids are reminded of it all the time? It does fit with the step of quotes we add in level 4, so it seems "logical" and it really makes programming easier, so I like this idea @OnnoEbbens!


Another option that @MarleenGilsing and me were brainstorming today about not allowing assignment as a backup option (so we'd allow `if naam is Henk print 'hallo'` but not `if naam is Henk getal is getal + 5`, which is also possible (not very easy to program but possible) and not all too limiting for kids (it'd just require [removing it the from examples](https://github.com/Felienne/hedy/pull/1732) as we think kids will not often think of it.

**Comment by MarleenGilsing** [comment] 2022-01-27 09:08
Felienne asked me to revisit this discussion. And I do think it's a tricky one. 

Onno's idea of adding the quotes in level 5 in the if command as well seems to make sense. The students have already learned how to use quotes and they know text needs quotes, so they could also apply that knowledge to the if command. Also Onno fairly says that it makes it easier to distinguish between text and variables. 

I agree with these points, however I have one big concern and that is the design goal to stay as close to natural language as possible. `if name is 'Hedy' print 'hello'` is obviously not very natural, and it would be more like normal languages without the quotes...
 
While typing this I just thought of another idea which might make it more natural and should solve the Pyhthon-translation-problem. What about adding the word `then`? I know it's used in other programming languages, not in python, but it is more natural then quotes...

if this then that. That souds very natural and (correct me if i'm wrong) it seems like Python should be able to recognize this word. The students wouldn't be hassled with quotes in the middle of their lines so much. It might also break up the long lines a bit more, and make them more readable.
And we could use it to teach the colon. We could say instead of then we now type : , because now the colon kind of comes out of nowhere except for 'this is how python does it'. 

Disadventages: This will impact the level structure (we might need a new level). The children will be taught a new (part of a) command that they need to learn, but doesn't add to the functionality (if works without then, so why teach then). It might seems natural to English and Dutch, but is this natural to the other languages too? 

@Felienne what do you think?

**Comment by Felienne** [comment] 2022-01-27 10:36
Ow @MarleenGilsing that is a very reasonable idea (I was hoping you would have an unreasonable idea so we could end the discussion sooner 🤣 ), and I *wish* that Python would use then, everything would be so much easier. (By the way, I love how you now understand parsing so well that you can guess that we could detect the `then` easily, you are right there)

Here is my best compromise: we only require the quotes when kid want to use multiple words for the check.

So legal are: 
*  `if name is Hedy print 'hello'`
*  `if name is 'Hedy' print 'hello'`
*  `if name is 'Hedy is het beste' print 'hello'` 

Illegal is:

*  `if name is Hedy is het beste print 'hello'` 

This I think has a nice balance between being doable and being reasonable. I will try my best to create a good error message for forgetting the quotes in this scenario but we will not always be able to.

@MarleenGilsing Can you update the teacher's guide to reflect this (maybe a good idea to go over the teacher's guide anyway?)

**Comment by MarleenGilsing** [comment] 2022-01-27 10:48
Haha sorry for being reasonable 😋 I think the compromise is alright. 

One question left: Do we teach the quotes right away and put them in our examples. Or do we keep the most natural language in our examples, which raises the question when we are going to explain the quotes. 

And yes, the teachers guide could definitely use an update. I'll take a look at it!

**Comment by Felienne** [comment] 2022-01-27 12:27
> 



> Haha sorry for being reasonable 😋 I think the compromise is alright.

Great! I will see how far I can get in building it

> One question left: Do we teach the quotes right away and put them in our examples. Or do we keep the most natural language in our examples, which raises the question when we are going to explain the quotes.

Great question! I will be a lot of info to show at the start, maybe we should explain it when we detect the error? Let me first build it and see how commonly we get errors and what types

> And yes, the teachers guide could definitely use an update. I'll take a look at it!

Thanks!

**Comment by Felienne** [comment] 2022-02-10 07:43
It was a lot of work but I think I made it as we want. Not using quotes on 2 words gives a nice error message:

![image](https://user-images.githubusercontent.com/1003685/153360369-9851259b-2595-4751-9945-6ce20b9e2acc.png)

These things all work:

![image](https://user-images.githubusercontent.com/1003685/153360421-cdbd3c0d-1c84-46dc-8040-ff4d52da9f63.png)

![image](https://user-images.githubusercontent.com/1003685/153360449-7fa8a351-ddfc-487f-8d3f-2469c50ab084.png)

![image](https://user-images.githubusercontent.com/1003685/153360472-8270be9f-5e56-4d7b-9a5d-724a38e5ac2e.png)

**Comment by thjazi39** [comment] 2022-02-13 06:31
I had an error a few days ago, and I want to talk about it here before creating an issue. 
Here is the code that doesn't work:
```
print 'Bienvenue chez Hedy !'
prix is 0
boisson is ask 'Que veux tu boire ?'
if boisson is coca prix is prix + 3
if boisson is eau prix is prix + 1
plat is ask 'Que veux tu manger ?'
if plat is hamburger prix is prix + 15
if plat is frites prix is prix + 6

print 'cela fera' prix 'euros !'
```
And here is the code that works:
```
print 'Bienvenue chez Hedy !'
prix is 0

boisson is ask 'Que veux tu boire ?'
if boisson is coca prix is prix + 3
if boisson is eau prix is prix + 1

plat is ask 'Que veux tu manger ?'
if plat is hamburger prix is prix + 15
if plat is frites prix is prix + 6

print 'cela fera' prix 'euros !'
```

I think the common point between this bug and the issue is an error in the interpretation of the 'else' or rather, when the 'else' does not exist.


Note that this bug also occurs at level 5 (which allows if/else). However, at level 5, even the 'good code' (the one that works at level 6) does not work

**Comment by Felienne** [comment] 2022-02-13 07:29
Thanks for checking @thjazi39. In principle making an issue is always ok, no reason not to, worse case we close it straight away. 

But... could you be more clear about what goes wrong? Cause for me the code works at level 5 and 6 too:

![image](https://user-images.githubusercontent.com/1003685/153743394-b94bfdb9-109b-411c-86fd-de177584c608.png)

This is in the current main/hedy-alpha. So where did you test, on the site or locally?

I suspect this is addressed by https://github.com/Felienne/hedy/pull/1817 and will be fixed when we release that.

Tip, you can use hedycode.com/version to see what changes have not yet been deployed.

**Comment by thjazi39** [comment] 2022-02-13 07:49
Indeed, I had tested on the online version, and not on the git, but by retesting on the git main, and well it works perfectly!

**Closed** 2022-04-07 14:15 UTC
