### ISSUE TITLE
Text after print seen as variable while not defined yet level-2

### ISSUE THREAD

**Issue by MarinusVanDijk** [Felienne/hedy#165] opened 2021-02-19 08:26 UTC
This work fine:

![image](https://user-images.githubusercontent.com/37830964/108477536-a04b9900-7293-11eb-884d-525e4bed5c28.png)

But now I like to print a title about the color exercise:

![image](https://user-images.githubusercontent.com/37830964/108477664-cf620a80-7293-11eb-87fe-e684cdc54f98.png)

I expect no errors since color is a text in line 1, not a variable? 

I expect this because the text after ask also contains a color string, so this should then also end up as an error.

**Comment by Felienne** [comment] 2021-02-19 09:36
Interesting expectation, don't think kids wil have this (haven't seen it in experiments) This will be cumbersome to fix because we now substitute all variables and this would require a slice (only underneath the relevant ask) to be substituted. I would say extremely low prio, but if you want to fix it yourself @MarinusVanDijk, feel free.

**Comment by Felienne** [comment] 2021-12-08 15:16
Duplicate of #1503

**Closed by Felienne** 2021-12-08 15:16 UTC
