### ISSUE TITLE
Command sleep cannot be followed by a variable

### ISSUE THREAD

**Issue by ericverschoor** [Felienne/hedy#1753] opened 2022-01-21 20:42 UTC
**Describe the bug**
Given the following program at level 2:

print Ik ben moe jij ook?
moe is ask Ben jij ook moe?
print Wat goed.
sleep
wacht is ask Over hoeveel seconden ga je slapen
print Ok... ik wacht wel even
sleep wacht
print Het is bedtijd  😴🛌

There is an unclear explanation why row 7, sleep wacht, is not not valid.
The  variable is defined in row 5 but is not recognized as a valid input for ‘sleep’

**Expected behavior**
I expect that a variable can be used after the sleep command

**What machine and browser you were using (optional)**
Safari on an Ipad Pro

![C80B2AFE-A2D8-495C-8589-29C753EEE198](https://user-images.githubusercontent.com/45706519/150598886-e412f08b-de49-4135-93df-19c5907a7293.jpeg)

**Comment by Felienne** [comment] 2022-01-22 14:26
Ah I see that this should be allow, or at the very least we should give a better error message! Will put this on my list

**Comment by Robernc** [comment] 2022-03-29 20:17
Hello @ericverschoor and @Felienne. I noticed that this was added to the list of 'Ongoing work for Core Team: This Week' on Feb 8.  I am interested in working on this issue and was wondering if it is possible to assign this issue to me?

**Comment by Felienne** [comment] 2022-03-30 06:16
> Hello @ericverschoor and @Felienne. I am interested in working on this issue and was wondering if it is possible to assign this issue to me? I did notice that this was added to the list of 'Ongoing work for Core Team: This Week' on Feb 8, so I am unsure if this assignment is allowed 

Yeah sometimes my todo list is more wishful thinking :) 

> I don't know the procedure for working on issues on the 'Ongoing work for Core Team' list.

We are also still figuring that out a bit on light of the new contributors but feel free to take this one (asking up front is *always* ok!)

**Comment by Robernc** [comment] 2022-04-08 01:14
@thjazi39. Thank you the @

**Comment by Robernc** [comment] 2022-04-22 23:41
@Felienne. I am sorry to report that I was unable to fix this issue due to time constraints on my part. Although, I did discover that a part of the issue is that in the lark parse-tree, sleep only accepts integers (picture of /hedy/grammars/level2-Additions.lark included below)
![image](https://user-images.githubusercontent.com/59849852/164816576-8c920ecb-1f42-4089-868e-e338379b3616.png)
I attempted to fix this issue by changing this to 
![image](https://user-images.githubusercontent.com/59849852/164817040-64a752f4-3b82-445a-bdb0-27c63410ce43.png)
```
//sleep
sleep: _SLEEP (_sleep_argument)?
_sleep_argument: (_SPACE | textwithoutspaces | NUMBER)*
```
I am unsure if this is the best possible solution due to my unfamiliarity with lark syntax (I used print, a few lines above, as a reference) (Image with print used for inspiration and changed sleep highlighted)
![image](https://user-images.githubusercontent.com/59849852/164816753-34f2693f-df33-476c-924a-3ef8ad113dc0.png)

This introduces a new issue where I was able to get the variable name but not its value within hedy.py so I was unable to get print to work. The new error is one from the print function not from hedy itself. (Image of the new issue included)
![image](https://user-images.githubusercontent.com/59849852/164816959-db57fbf7-80f4-44ab-9488-2f7ac91a64a5.png)
One possible solution would be to access the variable within hedy.py to get its value so that the sleep command will run properly. Here is my attempt to implement this solution
```
def sleep(self, args):
        if args == []:
            return "time.sleep(1)"
        else:
            if self.is_variable(args[0]):
                value = self.var_access(args)
                print(f"value in print: {value}")
                return f"time.sleep({value})"
            else:
                print(f"hi sleep with arg: {args}")
                return f"time.sleep({args[0]})"
```
(Side Note: This is one of my first attempts at submitting a pull request. Please let me know if this comment is too long or unhelpful)
Best of Luck

**Comment by Felienne** [comment] 2022-05-02 18:42
No problem @Robernc! We will pick this up further.

**Closed** 2022-05-10 11:47 UTC
