### ISSUE TITLE
When trying to run locally: Address already in use

### ISSUE THREAD

**Issue by dolfein** [Felienne/hedy#1271] opened 2021-11-15 00:55 UTC
Since today I am not able to run Hedy locally. Every time I try to start it I get the error that the address is already in use, even though there is no process running on that address (or any process running at all for that matter). Anyone knows what is going on here?

MacOS device.

```
Traceback (most recent call last):
  File "app.py", line 1209, in <module>
    app.run(threaded=True, debug=not is_in_debugger, port=config['port'], host="0.0.0.0")
  File "/Users/yunus/Documents/cs/thesis/hedy/.env/lib/python3.8/site-packages/flask/app.py", line 920, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Users/yunus/Documents/cs/thesis/hedy/.env/lib/python3.8/site-packages/werkzeug/serving.py", line 984, in run_simple
    s.bind(server_address)
OSError: [Errno 48] Address already in use
(.env) Yunuss-MacBook-Air:hedy yunus$ ps
  PID TTY           TIME CMD
  958 ttys001    0:00.03 /bin/bash -l
```

**Comment by Felienne** [comment] 2021-11-15 05:39
Hi @dolfein!

I can't seem to reproduce this problem locally, so I suspect you might still have a server running without being aware of it. Does a reboot help?

**Comment by dolfein** [comment] 2021-11-15 08:13
> Hi @dolfein!
> 
> I can't seem to reproduce this problem locally, so I suspect you might still have a server running without being aware of it. Does a reboot help?

A (quick) reboot did not fix it for me yesterday. I will  check later today if a long shutdown might fix it somehow.

**Comment by rix0rrr** [comment] 2021-11-15 08:58
Hi @dolfein ,

I see you're on a Mac. You can find out what process is using port `5000` (used by the local dev server) by running `lsof -i 4tcp:5000`. Looks like:

```
$ lsof -i 4tcp:5000
COMMAND     PID     USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
python3.9 32553 huijbers    3u  IPv4 0x16492726f98fe1f1      0t0  TCP *:commplex-main (LISTEN)
python3.9 33680 huijbers    3u  IPv4 0x16492726f98fe1f1      0t0  TCP *:commplex-main (LISTEN)
python3.9 33680 huijbers    4u  IPv4 0x16492726f98fe1f1      0t0  TCP *:commplex-main (LISTEN)
```

This tells me 2 processes with ids `32553` and `33680` are using that port.

I can then kill them using `kill -9`:

```
$ kill -9 32553 33680
```

**Comment by TiBiBa** [comment] 2021-11-15 20:47
I think we can close this issue as @rix0rrr has a clear explanation on how to solve this error locally.

**Closed by TiBiBa** 2021-11-15 20:47 UTC

**Comment by dolfein** [comment] 2021-11-15 21:23
There was indeed a process running on port 5000, thanks @rix0rrr.
Just in case anyone has the same problem in the future (recent MacOS update), this page explains what was running on that port and how to turn it off: https://utf9k.net/questions/macos-port-5000-monterey/
