### ISSUE TITLE
[BUG] Saving and loading personally created adventures fails

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#2354] opened 2022-03-29 10:01 UTC
I made an adventure for one of my classes. When students save the program in this adventure it does appear in the "my programs" list. However when they open the program all the code has disappeared. 

It seems as if the personally created adventures are not properly loaded when you open a program from "my programs". When I load other programs in the same level my personally created tab is not shown at first. Only when I refresh I can see it.

**Comment by TiBiBa** [comment] 2022-03-29 10:13
Hi @OnnoEbbens! Thanks for reporting this bug. I'm able to re-produce the first part as described and will look into it, it indeed seems to be an issue with loading and not with saving. The second part however I'm unable to re-produce. When in a class the selected teacher adventures are always shown for me (without a re-load) when I load another program in the same level.

**Comment by OnnoEbbens** [comment] 2022-03-29 10:24
Thanks for looking into this. As for the second part it is hard to pinpoint when this exactly happens. I tried a few times loading the personally created adventure and another adventure in the same level. Sometimes I do see the tab of the personally created adventure and sometimes I don't. After a refresh of the same page I always see the extra tab.

**Comment by TiBiBa** [comment] 2022-03-29 10:29
> Thanks for looking into this. As for the second part it is hard to pinpoint when this exactly happens. I tried a few times loading the personally created adventure and another adventure in the same level. Sometimes I do see the tab of the personally created adventure and sometimes I don't. After a refresh of the same page I always see the extra tab.

Weird! I still haven't encountered this bug, but good news: I did find the cause for the not loading bug. Will make a PR for this in a minute and hopefully it can be merged somewhere today.

**Closed** 2022-03-29 22:20 UTC
